version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: db_accesorios
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    command: >
      sh -c "
      php artisan config:cache &&
      php artisan migrate --force &&
      php artisan db:seed --force &&
      php artisan octane:start --server=swoole --host=0.0.0.0
      "

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_accesorios
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
