name: Deploy to Railway
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Railway CLI
        run: |
          npm install -g railway

      - name: Deploy to Railway
        run: railway up --service YOUR_SERVICE_ID
